FROM registry.fedoraproject.org/fedora-minimal:42
MAINTAINER Mario Vazquez <mavazque@redhat.com>

RUN set -x \
    && microdnf -y update \
    && microdnf install -y \
    gzip \
    jq \
    openssl \
    python3 \
    python3-flask \
    python3-pyOpenSSL \
    python3-requests \
    tar \
    && microdnf clean all \
    && rm -rf /var/cache/yum /var/cache/dnf \
    && curl -Ls https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz | \
    tar xfz - oc && mv oc /usr/bin/oc \
    && curl -Ls https://github.com/kubevirt/kubevirt/releases/download/v1.6.2/virtctl-v1.6.2-linux-amd64 -o /usr/bin/virtctl && chmod +x /usr/bin/virtctl \
    && mkdir -p /opt/fakefish/

# The stars in the command below will only copy those files if they exist
COPY --chown=1024 app/fakefish.py app/cert.pem* app/cert.key* /opt/fakefish/

ADD --chown=1024 app/templates /opt/fakefish/templates
ADD --chown=1024 kubevirt_scripts /opt/fakefish/custom_scripts

WORKDIR /opt/fakefish/

USER 1024

ENTRYPOINT ["/usr/bin/python3", "-u", "/opt/fakefish/fakefish.py"] 
